[package]
name = "rust-terminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
whoami = "1.5.1"
sysinfo = "0.30.12"